version: '2'

services:
  wojtek77-web:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - "../:/src"
      - "./nginx/config/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - wojtek77-php
  wojtek77-php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile-php-fpm
    volumes:
      - "../:/src"
      - "./php-fpm/config/php.ini:/usr/local/etc/php/php.ini"
  wojtek77-mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile-mysql
    volumes:
      - "./mysql/datadir:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  wojtek77-phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=wojtek77-mysql
    volumes:
      - /sessions
