FROM php:7.0-fpm
RUN apt-get update && apt-get -y install git unzip libicu-dev wget; \
    docker-php-ext-install -j$(nproc) bcmath intl pdo pdo_mysql && \
    pecl install xdebug-2.5.0 && \
    docker-php-ext-enable xdebug;
